[tox]
minversion = 3.18
envlist = py39

[testenv]
usedevelop = True
deps =
    -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/xena}
    setuptools
    oslotest
    stestr
commands =
    stestr run {posargs}

[testenv:lint]
skip_install = true
deps =
    ruff>=0.15.12
commands =
    ruff check {posargs:.}

[testenv:genconfig]
deps =
    {[testenv]deps}
commands =
    oslo-config-generator --config-file=tools/config/tunelo-config-generator.conf

[testenv:genpolicy]
deps =
    {[testenv]deps}
commands =
    oslopolicy-sample-generator --config-file=tools/policy/tunelo-policy-generator.conf
