[tox]
envlist = py39

[testenv]
setenv = VIRTUAL_ENV={envdir}
         PYTHONWARNINGS=default::DeprecationWarning
         PYTHONDONTWRITEBYTECODE=1
         LANGUAGE=en_US
         LC_ALL=en_US.UTF-8
         PYTHONUNBUFFERED=1

deps =
    -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/2023.1}
    -r test-requirements.txt
    setuptools<81
    .
commands =
    stestr run {posargs}

[testenv:genconfig]
commands =
    oslo-config-generator --config-file=tools/config/tunelo-config-generator.conf

[testenv:genpolicy]
commands =
    oslopolicy-sample-generator --config-file=tools/policy/tunelo-policy-generator.conf
