[DEFAULT]
output_file = etc/tunelo/tunelo.conf.sample
wrap_width = 62
namespace = tunelo
namespace = oslo.log
namespace = oslo.middleware.cors
namespace = oslo.middleware.http_proxy_to_wsgi
namespace = oslo.policy
namespace = oslo.reports
namespace = oslo.service.service
namespace = oslo.service.sslutils
namespace = keystonemiddleware.auth_token
namespace = osprofiler
